version: 2
updates:
  - package-ecosystem: docker
    directory: '/gamevm/base'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - 'type: dependencies'
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'