name: Release Drafter

on:
    push:
      branches: [ master ]
    schedule:
    - cron: "5 0 * * THU" #every thursday

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASES }}
