name: Build docker nvidia
#TODO: find a way to test client and server before running the docker container, seems effective in catching any errors
#FIXME: find a way to run this base image

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
jobs:
  build-go:
    name: Set up arc3dia executable
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout repo
        uses: actions/checkout@v4
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - 
        name: Download dependencies
        run: go get -v -t -d .
      - 
        name: Build binary
        run: go build -o arc3dia ./main.go
      -
       name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
         name: gobinary
         path: ./arc3dia
         retention-days: 5

  build-docker-base:
      name: Build base Docker image
      runs-on: ubuntu-latest
      needs:
        - build-go
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v4
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Download go binary
          uses: actions/download-artifact@v3
          with:
            name: gobinary
            path: ./
        - 
          name: Build Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./
            file: docker/base/Dockerfile
            push: false
            load: true
            tags: arc3dia:base
