name: Get screenshot of running container
#TODO: find a way to log errors from docker container onto github
#TODO: find a way to test client and server before running the docker container, seems effective in catching any errors
on:
  pull_request:

jobs:
  build-docker-image:
      name: Build docker image for testing
      runs-on: ubuntu-latest
              
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image with docker compose
          run: |
            cp docker/nvidia/Dockerfile .
            docker build -t qwantify:nvidia .