name: Get screenshot of running container
#TODO: find a way to log errors from docker container onto github
#TODO: find a way to test client and server before running the docker container, seems effective in catching any errors
on:
  pull_request:

jobs:
  build-docker-image:
      name: Build docker image for testing
      runs-on: ubuntu-latest
              
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v3
        
        - 
          name: Build docker image with docker compose
          working-directory: ./gamevm/base/
          run: docker build -t wanjohiryan/qwantify:latest .
        # -
        #   name: check if image is available
        #   run: docker image inspect wanjohiryan/qwantify:latest >/dev/null 2>&1 && echo yes || echo no 
        -
          name: Run container with docker compose
          run: docker compose up -d
        
        - 
          name: Install Dependencies
          uses: actions/setup-node@v3

        - 
          name: Install dependencies
          run: npm install puppeteer gif-encoder get-pixels
        
        - 
          name: Run puppeteer
          run: node .tests/test.js

        -
          name: Display contents of test.gif
          uses: actions/upload-artifact@v3
          with:
            name: screenshot
            path: test.gif
        
        - 
          name: Pull request artifacts
          uses: gavv/pull-request-artifacts@v1.0.0
          with:
            commit: ${{ github.event.pull_request.head.sha }}
            repo-token: ${{ github.token }}
            artifacts-branch: artifacts
            artifacts-dir: tests/pull-request-artifacts
            artifacts: |
              test.gif